### ISSUE TITLE
仓库太大下不动 可否优化下不必要文件

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-UXSDK-Beta-Android#14]

**Comment by dji-lisafedane** [comment]
Translation: 
the size of beta version SDK is too large to download and please advice us on how to optimize unnecessary files

**Comment by dji-lisafedane** [comment]
Please see this DJI Developer Forum article: **Tactical Guide - Reduce the size of your MSDK APK**: https://forum.dji.com/forum.php?mod=viewthread&tid=221836&extra=page%3D1
or the Chinese version: **【战术指导】编译APK的时候如何缩减APK的大小:** https://bbs.dji.com/forum.php?mod=viewthread&tid=242806

**Comment by dji-lisafedane** [comment]
The guides are for the MSDK but can be applied to your UX SDK project as it's built on top of the MSDK which also needs to be imported
