### ISSUE TITLE
Map Widget wiki fix

### ISSUE THREAD

**Issue by jeryini** [dji-sdk/Mobile-UXSDK-Beta-Android#17]
Hello!

Under Wiki page for [Map Widget](https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android/wiki/Map-Widget) where it specifies how to add different mapping providers, it says to add it to layout file via key `app:mapProvider`, but it should actually be under key `app:uxsdk_mapProvider`. Same holds true for key `mapBoxToken`, which should be `uxsdk_mapBoxToken`.

**Comment by alainpimentel** [comment]
Hey @jeryini! Thanks for telling us about this. We will update the documentation soon and I'll close this once we fix it.
