### ISSUE TITLE
Simulator indicator widget - Attitude data

### ISSUE THREAD

**Issue by jeryini** [dji-sdk/Mobile-UXSDK-Beta-Android#22]
Hello!

First of all, great job by providing [Simulator indicator widget](https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android/wiki/Simulator-Indicator-Widget), this really helps with debugging flight controller data without having to go outside to actually fly the drone :).

But I'm having some issue with Attitude data not being updated when calling `sendVirtualStickFlightControlData` method for controlling the aircraft. Here is an example:
```
FlightController flightController = djiDroneData.getFlightController();
                flightController.setVirtualStickAdvancedModeEnabled(true);
                flightController.setRollPitchControlMode(RollPitchControlMode.VELOCITY);
                flightController.setRollPitchCoordinateSystem(FlightCoordinateSystem.BODY);
                flightController.setVerticalControlMode(VerticalControlMode.VELOCITY);
                flightController.setYawControlMode(YawControlMode.ANGULAR_VELOCITY);

                djiDroneData.getFlightController().sendVirtualStickFlightControlData(
                        new FlightControlData(
                                mPitch, mRoll, mYaw, mThrottle
                        ), new CommonCallbacks.CompletionCallback() {
                            @Override
                            public void onResult(DJIError djiError) {
                                if (djiError != null) {
                                    Log.e(TAG, djiError.getDescription());
                                } else {
                                    Log.d(TAG, String.format("Attitude: %f %f %f %f", mPitch, mRoll, mYaw, mThrottle));
                                }
                            }
                        }
                );
```
This piece of code is being executed as a `TimerTask` with frequency 10HZ, so it should be enough. I have also tested it without Simulator and I can actually fly the drone via virtual joysticks. But for some reason when I have Simulator enabled and when I move the joysticks, I don't see the values under `Attitude` section changing that much, they are only changing slightly as they should if aircraft is hovering.

**Comment by dji-lisafedane** [comment]
Thanks for using the beta UX SDK and for bringing this to our attention.  We're investigating this now and will keep this thread updated.

**Comment by jeryini** [comment]
Hello @dji-lisafedane !

It seems it comes down to enabling virtual stick mode. If I use the following to enable advanced mode:
```
flightController.setVirtualStickAdvancedModeEnabled(true);
```
Then the commands are not being respected when I call `sendVirtualStickFlightControlData`. But if I call:
```
flightController.setVirtualStickModeEnabled(true, new CommonCallbacks.CompletionCallback() {
                    @Override
                    public void onResult(DJIError djiError) {
                        if (djiError != null) {
                            if (djiError.getDescription() != null) {
                                Log.e(TAG, djiError.getDescription());
                            }
                        }
                    }
                });
```
Then commands are working correctly and simulator also works as expected. It also works as expected either way of using `setVirtualStickAdvancedModeEnabled` or `setVirtualStickModeEnabled` if I use physical sticks.

**Comment by alainpimentel** [comment]
@jeryini glad you found the solution! Will close this issue but feel free to re-open if you still have any other problem with this widget.
