### ISSUE TITLE
Hooks for flight status widgets (Velocity/Distance/Altitude/...)

### ISSUE THREAD

**Issue by jeryini** [dji-sdk/Mobile-UXSDK-Beta-Android#23]
Hello!

It would help a lot if we could get hooks into telemetry based data in a similar way as it's done for [FPV-Widget](https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android/wiki/FPV-Widget#hooks). By telemetry data I mean widgets from **Dashboard** part, such as [Horizontal Velocity Widget](https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android/wiki/Horizontal-Velocity-Widget), Distance Home Widget, Vertical Velocity Widget, Altitude Widget, etc.

**Comment by alainpimentel** [comment]
Hey @jeryini, it's great to see you asking this because we have refactored the DashboardWidget for our upcoming release. We separated the telemetry into a new TelemetryPanel which will expose hooks for each individual widget.

**Comment by jeryini** [comment]
Hello @alainpimentel !

Nice to hear that, can't wait for your next release.
