### ISSUE TITLE
关于自定义widget

### ISSUE THREAD

**Issue by 781316853** [dji-sdk/Mobile-UXSDK-Beta-Android#3]
希望可以取消对widget进行宽高比的限定

**Comment by alainpimentel** [comment]
@781316853 The aspect ratio is just a recommendation. You should be able to resize a widget at will.
However, if you have issues with a specific widget, please post it here and we can take a look.

**Comment by 781316853** [comment]
例如对于dji.ux.widget.FlightModeWidget我的确可以自定义宽高,但是不能达到我需要的效果,似乎也不能设置gravity属性,因为这个控件的内容默认在左上角,是否有控件内容自适应控件宽高的方法

**Comment by alainpimentel** [comment]
Can please post a code sample of what you are trying to do? It will help us to better understand this issue. Thanks!

**Comment by 781316853** [comment]
<dji.ux.widget.FlightModeWidget
                android:layout_width="88dp"
                android:layout_height="22dp" />
对于这个控件,改变android:layout_width属性为44dp 22dp时,内容没有居中,希望能够开放gravity属性

**Comment by dji-lisafedane** [comment]
@781316853 - this is Lisa from DJI Developer Support.  Can you send us the issue on this form so we can look into this further for you? https://formcrafts.com/a/dji-developer-feedback-en

**Comment by alainpimentel** [comment]
@781316853 The package in your example `dji.ux.widget` is from UX SDK 4.  UX SDK 4 widgets are meant to be used as the documentation explains https://developer.dji.com/api-reference/android-uilib-api/Widgets/DUXFlightModeWidget.html?search=flightmodewi&i=0&. 

In this open source version of UX SDK 5 Beta 3 you can find a new version of the FlightModeWidget that can be resized as you wish, please check it out in https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android/wiki/Flight-Mode-Widget.
