### ISSUE TITLE
Removing markers or polylines from map (DJIMap)

### ISSUE THREAD

**Issue by bbenson09** [dji-sdk/Mobile-UXSDK-Beta-Android#57]
Is there really no way to remove markers or polylines from the map? Or am I missing something...?

Only way I can see to remove markers is to clear() the map, but this is not ideal as it makes the aircraft and fly zones disappear, too.

**Comment by kenargo** [comment]
.addPolyline(<polylineOptions) returns a DJIPolyline instance which contains a remove() function.  Is that what you are looking for?

**Comment by huhuanhuan** [comment]
At present, all methods based on mapbox are old. You need to rewrite and write the map control yourself, otherwise there will be many unknown restrictions

**Comment by bbenson09** [comment]
Ok, understood. Thank you!
