### ISSUE TITLE
MapBox SDK is VERY OLD (9.2.0 vs 10.3.0)

### ISSUE THREAD

**Issue by kenargo** [dji-sdk/Mobile-UXSDK-Beta-Android#59]
MapBox has release many security and performance updates over the years that the UI/UX SDK has been implemented and it appears that the current release has never been updated to integrate any of these changes.  Unfortunately, it isn't possible for the community to update the beta public domain code because a required body of code appears to be missing from the source tree (com.dji.mapkit.core.providers) and without this code it is not possible to initMapbox as the code has changed between the versions.

Any plans to either update the MapBox SDK or provide those classes?  Ideally the later as it would allow the community to grow the SDK.

**Comment by DJI-William** [comment]
Already report to the dev team.

**Comment by DJI-William** [comment]
We are about to switch to Maplibre in the future. We cannot upgrade the Mapbox SDK now as they require a Mapbox account which we don't have one.
