### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by jeryini** [dji-sdk/Mobile-UXSDK-Beta-Android#7]
Hello!

I get the following issue (`Android resource linking failed) when trying to build a project that has this library (`implementation 'com.github.dji-sdk:Mobile-UXSDK-Beta-Android:v0.3.0'`) defined as dependency:
```
AAPT: error: resource attr/uxsdk_cameraColorTextAppearance
AAPT: error: resource attr/uxsdk_cameraColorTextColor
AAPT: error: resource attr/uxsdk_cameraColorTextBackground
AAPT: error: resource attr/uxsdk_cameraColorTextSize
AAPT: error: resource attr/uxsdk_titleTextBackground
AAPT: error: resource attr/uxsdk_titleTextBackground
```
I noticed that exactly the same values are marked with `Cannot resolve symbol` errors also for this repository if you check it out. Though build completes successfully.

**Comment by alainpimentel** [comment]
@jeryini thanks for finding this. We were able to reproduce this and we are working on a fix.

**Comment by jeryini** [comment]
Great, in the mean time I managed to solve it by specifying attr fields in `src/main/res/values/attrs.xml`:
```
    <attr name="uxsdk_cameraColorTextAppearance" />
    <attr name="uxsdk_cameraColorTextColor" />
    <attr name="uxsdk_cameraColorTextBackground" />
    <attr name="uxsdk_cameraColorTextSize" />
    <attr name="uxsdk_titleTextBackground" />
```

**Comment by alainpimentel** [comment]
Hi @jeryini, the new beta 3.1 release is out! Thanks for the feedback and feel free to post more issues if you find anything else in the future 👍
