### ISSUE TITLE
A DJI Menbership is need for apply UXSDK Key ?

### ISSUE THREAD

**Issue by wuyan12138** [dji-sdk/Mobile-UXSDK-Beta-Android#9]
If I want to use DJI UXSDK in my Android Project, I need a DJI Key, for UXSDK, is a menber ship necessary if I want to apply a key ? Now I just can apply key for mobile SDK.Can I use mobile SDK's key in a UX SDK project ?

**Comment by siddutgikar** [comment]
UXSDK has been built on top of DJI-MobileSDK. Thus, you don't need a separate key for UXSDK. You can continue to use the key created for DJI-MobileSDK. 
For reference please check [Sample Manifest file](https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android/blob/master/android-uxsdk-beta-sample/src/main/AndroidManifest.xml). 
If you need to create a new DJI-MobileSDK key please follow these [steps.](https://developer.dji.com/mobile-sdk/documentation/quick-start/index.html)

**Comment by alainpimentel** [comment]
Marking as closed since the question has been answered.
